apiVersion: v1
kind: Service
metadata:
  name: flask-quiz
  labels:
    app: flask-quiz
spec:
  type: NodePort
  selector:
    app: flask-quiz
  ports:
    - protocol: TCP
      port: 80
      targetPort: 5000
      nodePort: 30500

