name: Deploy to Kubernetes

on:
  push:
    branches: [main]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Log in to Docker Hub
        run: echo "Espadon1988!" | docker login -u "saint1334" --password-stdin

      - name: Build Docker image
        run: docker build -t your-dockerhub/flask-quiz:latest .

      - name: Push image to Docker Hub
        run: docker push your-dockerhub/flask-quiz:latest

      - name: Set up kubectl
        uses: azure/setup-kubectl@v3
        with:
          version: 'v1.28.0'

      - name: Set up Helm
        uses: azure/setup-helm@v3
        with:
          version: 'v3.13.0'

      - name: Configure kubeconfig
        run: |
          mkdir -p ~/.kube
          echo "${{ secrets.KUBE_CONFIG }}" > ~/.kube/config

      - name: Deploy with Helm
        run: helm upgrade --install flask-quiz ./helm-chart --namespace flask --create-namespace

